### ISSUE TITLE
Design beautiful, unscary error pages

### ISSUE THREAD

**Issue by mbmjertan** [pulsir/pulsir4#12]
Basically, not this:
![screen shot 2017-07-06 at 00 24 01](https://user-images.githubusercontent.com/1742806/27887532-78bac850-61e1-11e7-909a-0b6ef2967a70.png)

**Comment by jevtovich** [comment]
That's all working, it's just that we didn't enable extensions in our host..

**Comment by ghost** [comment]
Done
